inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'log/*'
    - 'public/*'

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false